spring:
    application:
        name: standalone
    datasource:
        url: jdbc:h2:mem:testdb
        username: test
        password: test
        jpa:
            database-platform: org.hibernate.dialect.H2Dialect
            hibernate:
                ddl-auto: update
            properties:
                hibernate:
                    format_sql: true
            show-sql: false
        h2:
            console:
                enabled: true

workerId: test
